const NewsActions = {
    GET_TRENDING_NEWS_REQUEST: "GET_TRENDING_NEWS_REQUEST",
    GET_TRENDING_NEWS: "GET_TRENDING_NEWS",
    GET_TRENDING_NEWS_FAILURE: "GET_TRENDING_NEWS_FAILURE",
}

export default NewsActions;