const RetailerSubscriptionActions = {
    REQUEST_REGISTER_EMAIL: "REQUEST_REGISTER_EMAIL",
    SUCCESS_REGISTER_EMAIL: "SUCCESS_REGISTER_EMAIL",
    FAILURE_REGISTER_EMAIL: "FAILURE_REGISTER_EMAIL",

    SHOW_THANK_YOU_MESSAGE: "SHOW_THANK_YOU_MESSAGE",
    HIDE_THANK_YOU_MESSAGE: "HIDE_THANK_YOU_MESSAGE",
}

export default RetailerSubscriptionActions;